# Upstash / Local Redis Configuration
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.password=${REDIS_PASSWORD:}
spring.data.redis.ssl.enabled=${REDIS_SSL_ENABLED:false}

# Microservice Target URLs
user.service.url=${USER_SERVICE_URL:http://localhost:8081}
payment.service.url=${PAYMENT_SERVICE_URL:http://localhost:8082}
transaction.service.url=${TRANSACTION_SERVICE_URL:http://localhost:8083}
notification.service.url=${NOTIFICATION_SERVICE_URL:http://localhost:8084}
worker.service.url=${WORKER_SERVICE_URL:http://localhost:8085}
