spring.application.name=api-gateway
spring.data.redis.host=${REDIS_HOST:<your-upstash-redis-endpoint>.upstash.io}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.password=${REDIS_PASSWORD:<your-upstash-password>}
spring.data.redis.ssl.enabled=true


server.port=8080
