spring.application.name=payment-service

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/payment_gateway}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:password}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Redis URL Configuration
spring.data.redis.url=${REDIS_URL:redis://localhost:6379}

# Microservice Target URLs
user.service.url=${USER_SERVICE_URL:http://localhost:8081}
transaction.service.url=${TRANSACTION_SERVICE_URL:http://localhost:8083}
notification.service.url=${NOTIFICATION_SERVICE_URL:http://localhost:8084}

server.port=8082
server.servlet.context-path=/api
